/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NeoscryptWrapper */

#ifndef _Included_NeoscryptWrapper
#define _Included_NeoscryptWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NeoscryptWrapper
 * Method:    printText
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NeoscryptWrapper_printText
  (JNIEnv *, jobject);

/*
 * Class:     NeoscryptWrapper
 * Method:    neoscrypt
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_NeoscryptWrapper_neoscrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
